apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
 name: success-rate
spec:
 metrics:
 - name: success-rate
   successCondition: result[0] <= 5
   provider:
     prometheus:
       address: "http://10.182.0.40/:"
       query: |
         sum(netdata_haproxy_f_hrsp_4xx_responses_persec_average{job="PGP-Prod-boss-haproxy"})


