apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
 name: success-rate
spec:
 args:
 - name: service-name
 - name: prometheus-port
   value: 9090
 metrics:
 - name: success-rate
   successCondition: result[0] >= 20
   provider:
     prometheus:
       address: "http://http://10.182.0.40/:"
       query: |
         sum(netdata_haproxy_f_hrsp_4xx_responses_persec_average{job="PGP-Prod-boss-haproxy"})


